import React, { createContext, useContext, useState, useEffect } from "react";

const LANGUAGE_STORAGE_KEY = "finguard_app_language";

export const SUPPORTED_LANGUAGES = [
  { code: "en", name: "English", nativeName: "English", flag: "🇺🇸", locale: "en-US" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", flag: "🇮🇳", locale: "ta-IN" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", flag: "🇮🇳", locale: "hi-IN" },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸", locale: "es-ES" },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷", locale: "fr-FR" },
  { code: "de", name: "German", nativeName: "Deutsch", flag: "🇩🇪", locale: "de-DE" },
];

export const TRANSLATIONS = {
  en: {
    // Navigation
    dashboard: "Dashboard",
    invoices: "Invoices",
    expenses: "Expenses",
    transactions: "Transactions",
    customers: "Customers",
    payments: "Payments",
    credit: "Credit",
    advisor: "AI Advisor",
    reports: "Reports",
    settings: "Settings",
    collapse: "Collapse",
    logout: "Log out",
    editProfile: "Edit Profile",
    accountSettings: "Account & Settings",

    // Topbar
    searchPlaceholder: "Search transactions, invoices…",
    notifications: "Notifications",
    language: "Language",
    selectLanguage: "Select Language",

    // Timeframes
    "30 days": "30 days",
    "This month": "This month",
    "Last 3 months": "Last 3 months",
    "This fiscal year": "This fiscal year",

    // Dashboard Overview
    activePeriod: "Active Period",
    liveCalculated: "Live Calculated",
    overviewTitle: "Financial Overview",
    totalRevenue: "Total Revenue",
    monthlyInflow: "Monthly Inflow",
    operatingExpenses: "Operating Expenses",
    netCashFlow: "Net Cash Flow",
    runwayEstimate: "Cash Runway",
    runwayMonths: "months runway at current burn",
    aiAdvisorTitle: "FinGuard AI Advisor",
    aiAdvisorSubtitle: "Live business intelligence & cash alerts",
    revenueVsExpenses: "Revenue vs Expenses",
    comparison: "Comparison",
    revenue: "Revenue",
    expenses: "Expenses",
    monthlyCashFlow: "Monthly Cash Flow",
    netCashPosition: "Net cash position, in ₹ thousands",
    netCash: "Net Cash",
    expenseBreakdown: "Expense Breakdown",
    shareOfTotalSpend: "Share of total spend",
    paymentStatus: "Payment Status",
    invoicesThisPeriod: "Invoices this period",
    recentTransactions: "Recent Transactions",
    viewAll: "View all",
    transaction: "Transaction",
    category: "Category",
    date: "Date",
    amount: "Amount",
    status: "Status",
    recentInvoices: "Recent Invoices",
    due: "Due",
    preview: "Preview",
    spendingScore: "Spending Score",
    creditScore: "Credit Score",
    creditUtilization: "Credit Utilization",
    monthlySpendingTrend: "Monthly Spending Trend",
    last6Months: "Last 6 months",
    ptsVsLastMonth: "pts vs last month",

    // Invoices Page
    invoicesTitle: "Invoices & Billings",
    smartUploadAi: "Smart Upload (AI)",
    addManual: "Add manual",
    searchInvoices: "Search customer or invoice ID",
    all: "All",
    paid: "Paid",
    sent: "Sent",
    dueSoon: "Due soon",
    overdue: "Overdue",
    draft: "Draft",
    aiImported: "AI Imported",
    noInvoicesFound: "No invoices found",
    noInvoicesDesc: "Try a different filter or search term, or upload a new invoice.",
    invoiceColumn: "Invoice",
    customerColumn: "Customer",
    dueDateColumn: "Due date",
    amountColumn: "Amount",
    statusColumn: "Status",
    actionsColumn: "Actions",
    viewDetails: "View Details",

    // Invoice Detail & Reminder Modal
    invoiceDetailsTitle: "Invoice Details",
    invoiceOverviewTab: "Invoice Overview & Items",
    remindCustomerTab: "Remind Customer (Mail / WhatsApp)",
    remindToPay: "Remind to Pay",
    markAsPaid: "Mark as Paid",
    markAsUnpaid: "Mark as Unpaid",
    billedTo: "Billed To (Customer)",
    scheduleTerms: "Schedule & Terms",
    invoiceDate: "Invoice Date",
    terms: "Terms",
    totalAmountDue: "Total Amount Due",
    itemizedBreakdown: "Itemized Breakdown",
    items: "items",
    qty: "Qty",
    subtotal: "Subtotal",
    discount: "Discount",
    gstTax: "GST Tax",
    totalDue: "Total Due",
    reminderActivityLog: "Reminder Activity Log",
    reminded: "Reminded",
    printInvoice: "Print Invoice",
    chooseChannel: "1. Select Communication Channel",
    whatsAppDirect: "WhatsApp Direct",
    emailMailto: "Email (Mailto)",
    aiWorkflow: "AI Workflow",
    targetRecipient: "Target Recipient",
    pendingDue: "Pending Due",
    chooseTone: "2. Choose Tone",
    friendly: "Friendly",
    urgent: "Urgent",
    official: "Official",
    workflowWebhookUrl: "Workflow Webhook URL",
    hideJson: "Hide JSON",
    viewJsonPayload: "View JSON Payload",
    reminderDraft: "3. Reminder Message Draft",
    copyText: "Copy Text",
    copied: "Copied!",
    backToInvoice: "Back to Invoice",
    sendOnWhatsApp: "Send on WhatsApp",
    openEmailClient: "Open in Email Client",
    triggerWorkflowWebhook: "Trigger AI Workflow Webhook",
    triggeringWorkflow: "Triggering Workflow...",
    close: "Close",
    cancel: "Cancel",

    // Smart Upload Modal
    smartUploadModalTitle: "Smart Invoice & Receipt Scanner",
    neuralOcrActive: "Neural OCR Active",
    smartUploadSubtext: "Reads invoice images & PDFs directly, extracting accurate line items and customer details",
    dragDropText: "Drag and drop your Invoice Image or PDF here",
    dragDropSubtext: "Upload ABC Grocery or any invoice/receipt to automatically scan and extract all items and totals.",
    browseImageOrPdf: "Browse Image or PDF",
    supportedFormats: "Supported Formats",
    pdfDocuments: "PDF Documents",
    sampleTemplates: "Or try with sample templates:",
    intelligentOcrScanner: "Intelligent OCR Scanner",
    ocrInfoBanner: "FinGuard AI reads text and numerical tables directly from your uploaded invoice images and receipts, automatically parsing items, quantities, prices, taxes, and customer details.",
    readingInvoice: "FinGuard AI is reading your invoice...",
    neuralOcrAnalysis: "Neural OCR Analysis",
    scanStep1: "Streaming binary file & initializing OCR scanner",
    scanStep2: "Neural OCR: Reading text tokens, lines & items",
    scanStep3: "Detecting customer (Billed To / Ship To) & dates",
    scanStep4: "Calculating line item quantities, taxes & subtotal",
    scanStep5: "Syncing structured record to FinGuard UI",
    uploadAnother: "Upload another",
    extractedInvoiceDetails: "Extracted Invoice Details",
    clickToEdit: "Click any field to edit",
    invoiceNumber: "Invoice Number",
    customerName: "Customer Name (Billed To)",
    contactEmail: "Contact Email",
    phoneNumber: "Phone Number",
    billingAddress: "Billing Address",
    extractedItems: "Extracted Items",
    addItem: "Add Item",
    gstTaxRate: "GST Tax Rate (%)",
    documentPreview: "Document Preview",
    uploadedImagePreview: "Uploaded Image",
    taxInvoicePreview: "Tax Invoice",
    ocrVerifiedText: "Optical text recognition and totals verified",
    backToUpload: "Back to Upload",
    reviewAndAddInvoice: "Review & Add Invoice",

    // Settings
    settingsDesc: "Manage your personal profile, business information, language preferences, and notifications.",
    languageSettings: "Language & Regional Settings",
    languageDescription: "Choose your preferred language. All financial analytics, navigation, and invoice tools will immediately update.",
    languageChangedTo: "Language changed to",
    userProfile: "User Profile",
    editProfileDetails: "Edit profile details",
    businessAccountDetails: "Business & Account Details",
    yourFullName: "Your full name",
    roleDesignation: "Role / Designation",
    businessName: "Business name",
    profileSavedMsg: "Business & profile changes saved.",
    signedOutMsg: "You have been signed out.",
    saveChanges: "Save changes",
    notifInvoiceDue: "Alert me when invoices are due soon",
    notifWeeklySummary: "Send a weekly financial summary",
    notifCreditAlerts: "Notify me of credit utilization changes",
    securityAndDatabase: "Security & Dummy Database",
    persistentDatabase: "Persistent Local Database",
    registeredAccountsStored: "registered user account(s) stored in database",
    activeStorage: "Active Storage",
    registeredAccountsInDb: "Registered Accounts in Dummy Database:",
    current: "Current",
    sessionActiveFor: "Session active for",

    // AI Advisor Panel Insights
    insight1: "ABC Grocery cash flow improved by 14.2% following recent receivables clearance.",
    insight2: "3 vendor payments due this week totaling ₹12,400. Sufficient liquidity available.",
    insight3: "Tax optimization opportunity: Advance GST claim eligible for ₹4,200 on equipment invoice.",
    insight4: "Credit rating improved to AAA Prime with 98.4% on-time settlement score.",

    // Expense Categories
    "Engineering & Infra": "Engineering & Infra",
    "Cloud & Hosting": "Cloud & Hosting",
    "Office & Workspace": "Office & Workspace",
    "Marketing & Growth": "Marketing & Growth",
    "Payroll & Legal": "Payroll & Legal",
    "Other Operating": "Other Operating",
    "Software & Subscriptions": "Software & Subscriptions",
    "Design & Creative": "Design & Creative",
    "Travel & Logistics": "Travel & Logistics",
    "Office Supplies": "Office Supplies",
    "Hardware & Servers": "Hardware & Servers",
    "Security & Audits": "Security & Audits",
    "Professional Fees": "Professional Fees",
  },

  ta: {
    // Navigation (தமிழ்)
    dashboard: "முகப்பு பலகை",
    invoices: "விலைப்பட்டியல்கள்",
    expenses: "செலவுகள்",
    transactions: "பரிவர்த்தனைகள்",
    customers: "வாடிக்கையாளர்கள்",
    payments: "பணப்பரிமாற்றங்கள்",
    credit: "கடன் மதிப்பீடு",
    advisor: "AI நிதி ஆலோசகர்",
    reports: "அறிக்கைகள்",
    settings: "அமைப்புகள்",
    collapse: "சுருக்கு",
    logout: "வெளியேறு",
    editProfile: "சுயவிவரம் திருத்து",
    accountSettings: "கணக்கு & அமைப்புகள்",

    // Topbar
    searchPlaceholder: "பரிவர்த்தனைகள், இன்வாய்ஸ்களைத் தேடுங்கள்…",
    notifications: "அறிவிப்புகள்",
    language: "மொழி",
    selectLanguage: "மொழியைத் தேர்ந்தெடுக்கவும்",

    // Timeframes
    "30 days": "30 நாட்கள்",
    "This month": "இந்த மாதம்",
    "Last 3 months": "கடந்த 3 மாதங்கள்",
    "This fiscal year": "நடப்பு நிதி ஆண்டு",

    // Dashboard Overview
    activePeriod: "செயலில் உள்ள காலம்",
    liveCalculated: "நேரலை கணக்கீடு",
    overviewTitle: "நிதி மேலோட்டம்",
    totalRevenue: "மொத்த வருவாய்",
    monthlyInflow: "மாதாந்திர வரவு",
    operatingExpenses: "இயக்கச் செலவுகள்",
    netCashFlow: "நிகர பணப்புழக்கம்",
    runwayEstimate: "நிதி இருப்பு காலம்",
    runwayMonths: "மாதங்கள் தற்போதைய செலவில் இருப்பு",
    aiAdvisorTitle: "FinGuard AI நிதி ஆலோசகர்",
    aiAdvisorSubtitle: "நேரலை வணிக நுண்ணறிவு & எச்சரிக்கைகள்",
    revenueVsExpenses: "வருவாய் vs செலவுகள்",
    comparison: "ஒப்பீடு",
    revenue: "வருவாய்",
    expenses: "செலவுகள்",
    monthlyCashFlow: "மாதாந்திர பணப்புழக்கம்",
    netCashPosition: "நிகர பண நிலை, ₹ ஆயிரங்களில்",
    netCash: "நிகர பணம்",
    expenseBreakdown: "செலவு விவரங்கள்",
    shareOfTotalSpend: "மொத்த செலவில் பங்கு",
    paymentStatus: "செலுத்தல் நிலை",
    invoicesThisPeriod: "இக்காலக்கட்ட இன்வாய்ஸ்கள்",
    recentTransactions: "சமீபத்திய பரிவர்த்தனைகள்",
    viewAll: "அனைத்தையும் காண்க",
    transaction: "பரிவர்த்தனை",
    category: "வகை",
    date: "தேதி",
    amount: "தொகை",
    status: "நிலை",
    recentInvoices: "சமீபத்திய இன்வாய்ஸ்கள்",
    due: "கடைசி தேதி",
    preview: "முன்னோட்டம்",
    spendingScore: "செலவு மதிப்பீடு",
    creditScore: "கடன் மதிப்பீடு",
    creditUtilization: "கடன் பயன்பாடு",
    monthlySpendingTrend: "மாதாந்திர செலவு போக்கு",
    last6Months: "கடந்த 6 மாதங்கள்",
    ptsVsLastMonth: "புள்ளிகள் கடந்த மாதத்தை விட",

    // Invoices Page
    invoicesTitle: "இன்வாய்ஸ்கள் & பில்லிங்",
    smartUploadAi: "ஸ்மார்ட் அப்லோட் (AI)",
    addManual: "கைமுறை பதிவு",
    searchInvoices: "வாடிக்கையாளர் அல்லது இன்வாய்ஸ் எண் தேடுங்கள்",
    all: "அனைத்தும்",
    paid: "செலுத்தப்பட்டது",
    sent: "அனுப்பப்பட்டது",
    dueSoon: "விரைவில் செலுத்த வேண்டியவை",
    overdue: "காலக்கெடு முடிந்தது",
    draft: "வரைவு",
    aiImported: "AI இறக்குமதி",
    noInvoicesFound: "இன்வாய்ஸ்கள் எதுவும் கிடைக்கவில்லை",
    noInvoicesDesc: "வேறு தேடல் வார்த்தையைப் பயன்படுத்தவும் அல்லது புதிய இன்வாய்ஸை பதிவேற்றவும்.",
    invoiceColumn: "விலைப்பட்டியல்",
    customerColumn: "வாடிக்கையாளர்",
    dueDateColumn: "கடைசி தேதி",
    amountColumn: "தொகை",
    statusColumn: "நிலை",
    actionsColumn: "செயல்கள்",
    viewDetails: "விவரங்களைக் காண்க",

    // Invoice Detail & Reminder Modal
    invoiceDetailsTitle: "விலைப்பட்டியல் விவரங்கள்",
    invoiceOverviewTab: "இன்வாய்ஸ் கண்ணோட்டம் & பொருட்கள்",
    remindCustomerTab: "வாடிக்கையாளருக்கு நினைவூட்டு (மின்னஞ்சல் / WhatsApp)",
    remindToPay: "பணம் செலுத்த நினைவூட்டு",
    markAsPaid: "செலுத்தப்பட்டதாகக் குறிக்கவும்",
    markAsUnpaid: "செலுத்தப்படாததாக மாற்றவும்",
    billedTo: "பெறுநர் (வாடிக்கையாளர்)",
    scheduleTerms: "காலக்கெடு & நிபந்தனைகள்",
    invoiceDate: "விலைப்பட்டியல் தேதி",
    terms: "விதிமுறைகள்",
    totalAmountDue: "செலுத்த வேண்டிய மொத்தத் தொகை",
    itemizedBreakdown: "பொருட்கள் விவரப் பட்டியல்",
    items: "பொருட்கள்",
    qty: "அளவு",
    subtotal: "கூட்டுத்தொகை",
    discount: "தள்ளுபடி",
    gstTax: "ஜி.எஸ்.டி வரி",
    totalDue: "மொத்த நிலுவை",
    reminderActivityLog: "நினைவூட்டல் செயல்பாட்டுப் பதிவு",
    reminded: "நினைவூட்டப்பட்டது",
    printInvoice: "விலைப்பட்டியலை அச்சிடுக",
    chooseChannel: "1. தொடர்பு ஊடகத்தைத் தேர்ந்தெடுக்கவும்",
    whatsAppDirect: "நேரடி WhatsApp",
    emailMailto: "மின்னஞ்சல் (Mailto)",
    aiWorkflow: "AI தானியங்கி பணிப்பாய்வு",
    targetRecipient: "பெறும் வாடிக்கையாளர்",
    pendingDue: "நிலுவைத் தொகை",
    chooseTone: "2. குரல் பாணியைத் தேர்வுசெய்க",
    friendly: "நட்புடன்",
    urgent: "அவசரம்",
    official: "அலுவல்முறை",
    workflowWebhookUrl: "பணிப்பாய்வு வெப்ஹூக் URL",
    hideJson: "JSON மறை",
    viewJsonPayload: "JSON பேலோடைப் பார்",
    reminderDraft: "3. நினைவூட்டல் செய்தி வரைவு",
    copyText: "உரையை நகலெடு",
    copied: "நகலெடுக்கப்பட்டது!",
    backToInvoice: "விலைப்பட்டியலுக்குத் திரும்பு",
    sendOnWhatsApp: "WhatsApp மூலம் அனுப்பு",
    openEmailClient: "மின்னஞ்சல் செயலியில் திற",
    triggerWorkflowWebhook: "AI பணிப்பாய்வு வெப்ஹூக்கை இயக்கு",
    triggeringWorkflow: "பணிப்பாய்வு இயக்கப்படுகிறது...",
    close: "மூடு",
    cancel: "ரத்து செய்",

    // Smart Upload Modal
    smartUploadModalTitle: "ஸ்மார்ட் இன்வாய்ஸ் & ரசீது ஸ்கேனர்",
    neuralOcrActive: "நியூரல் OCR இயங்குகிறது",
    smartUploadSubtext: "இன்வாய்ஸ் படங்கள் மற்றும் PDF-களை நேரடியாகப் படித்து, துல்லியமான பொருட்கள் மற்றும் வாடிக்கையாளர் விவரங்களை எடுக்கிறது",
    dragDropText: "இன்வாய்ஸ் படம் அல்லது PDF கோப்பை இங்கே இழுத்து விடவும்",
    dragDropSubtext: "ABC Grocery அல்லது எந்தவொரு ரசீதையும் தானாக ஸ்கேன் செய்து பொருட்கள் மற்றும் மொத்த தொகையை பிரித்தெடுக்கவும்.",
    browseImageOrPdf: "படம் அல்லது PDF-ஐ உலாவுக",
    supportedFormats: "ஆதரிக்கப்படும் வடிவங்கள்",
    pdfDocuments: "PDF ஆவணங்கள்",
    sampleTemplates: "அல்லது மாதிரி ஆவணங்களுடன் முயற்சிக்கவும்:",
    intelligentOcrScanner: "நுண்ணறிவு OCR ஸ்கேனர்",
    ocrInfoBanner: "FinGuard AI உங்கள் பதிவேற்றிய இன்வாய்ஸ் படங்கள் மற்றும் ரசீதுகளிலிருந்து உரை மற்றும் அட்டவணைகளை நேரடியாகப் படித்து, பொருட்கள், அளவுகள், விலைகள், வரிகள் மற்றும் வாடிக்கையாளர் விவரங்களை தானாகப் பிரிக்கிறது.",
    readingInvoice: "FinGuard AI உங்கள் விலைப்பட்டியலைப் படிக்கிறது...",
    neuralOcrAnalysis: "நியூரல் OCR பகுப்பாய்வு",
    scanStep1: "பைனரி கோப்பை ஸ்ட்ரீம் செய்து OCR ஸ்கேனரைத் தொடங்குதல்",
    scanStep2: "நியூரல் OCR: உரை டோக்கன்கள், வரிகள் & பொருட்களைப் படித்தல்",
    scanStep3: "வாடிக்கையாளர் & தேதிகளைக் கண்டறிதல்",
    scanStep4: "பொருட்களின் அளவுகள், வரிகள் மற்றும் கூட்டுத்தொகையைக் கணக்கிடுதல்",
    scanStep5: "கட்டமைக்கப்பட்ட பதிவை FinGuard உடன் ஒத்திசைத்தல்",
    uploadAnother: "மற்றொன்றைப் பதிவேற்று",
    extractedInvoiceDetails: "பிரித்தெடுக்கப்பட்ட விலைப்பட்டியல் விவரங்கள்",
    clickToEdit: "திருத்த எந்த புலத்தையும் கிளிக் செய்யவும்",
    invoiceNumber: "விலைப்பட்டியல் எண்",
    customerName: "வாடிக்கையாளர் பெயர்",
    contactEmail: "தொடர்பு மின்னஞ்சல்",
    phoneNumber: "தொலைபேசி எண்",
    billingAddress: "பில்லிங் முகவரி",
    extractedItems: "பிரித்தெடுக்கப்பட்ட பொருட்கள்",
    addItem: "பொருள் சேர்",
    gstTaxRate: "ஜி.எஸ்.டி வரி விகிதம் (%)",
    documentPreview: "ஆவண முன்னோட்டம்",
    uploadedImagePreview: "பதிவேற்றிய படம்",
    taxInvoicePreview: "வரி விலைப்பட்டியல்",
    ocrVerifiedText: "ஒளியியல் உரை அறிதல் மற்றும் மொத்தங்கள் சரிபார்க்கப்பட்டன",
    backToUpload: "மீண்டும் பதிவேற்று",
    reviewAndAddInvoice: "சரிபார்த்து இன்வாய்ஸ் சேர்",

    // Settings
    settingsDesc: "உங்கள் சுயவிவரம், வணிகத் தகவல், மொழி விருப்பங்கள் மற்றும் அறிவிப்புகளை நிர்வகிக்கவும்.",
    languageSettings: "மொழி & பிராந்திய அமைப்புகள்",
    languageDescription: "உங்கள் விருப்ப மொழியைத் தேர்ந்தெடுக்கவும். அனைத்து நிதி பகுப்பாய்வுகள், வழிசெலுத்தல் மற்றும் இன்வாய்ஸ் கருவிகள் உடனடியாக புதுப்பிக்கப்படும்.",
    languageChangedTo: "மொழி மாற்றப்பட்டது:",
    userProfile: "பயனர் சுயவிவரம்",
    editProfileDetails: "சுயவிவர விவரங்களைத் திருத்து",
    businessAccountDetails: "வணிகம் & கணக்கு விவரங்கள்",
    yourFullName: "உங்கள் முழு பெயர்",
    roleDesignation: "பதவி / பதவிப் பெயர்",
    businessName: "வணிகப் பெயர்",
    profileSavedMsg: "வணிகம் & சுயவிவர மாற்றங்கள் சேமிக்கப்பட்டன.",
    signedOutMsg: "நீங்கள் வெளியேறிவிட்டீர்கள்.",
    saveChanges: "மாற்றங்களைச் சேமிக்கவும்",
    notifInvoiceDue: "இன்வாய்ஸ் காலம் முடிவடையும் போது எச்சரிக்கவும்",
    notifWeeklySummary: "வாராந்திர நிதி சுருக்கத்தை அனுப்பவும்",
    notifCreditAlerts: "கடன் பயன்பாட்டு மாற்றங்களை எனக்கு அறிவிக்கவும்",
    securityAndDatabase: "பாதுகாப்பு & மாதிரி தரவுத்தளம்",
    persistentDatabase: "நிலைத்த உள்ளூர் தரவுத்தளம்",
    registeredAccountsStored: "பதிவுசெய்யப்பட்ட கணக்குகள் தரவுத்தளத்தில் உள்ளன",
    activeStorage: "செயலில் உள்ள சேமிப்பு",
    registeredAccountsInDb: "மாதிரி தரவுத்தளத்தில் பதிவுசெய்யப்பட்ட கணக்குகள்:",
    current: "தற்போதையது",
    sessionActiveFor: "செயலில் உள்ள அமர்வு:",

    // AI Advisor Panel Insights
    insight1: "சமீபத்திய வரவுகளை அடுத்து ஏபிசி மளிகைக் கடையின் பணப்புழக்கம் 14.2% அதிகரித்துள்ளது.",
    insight2: "இந்த வாரம் ₹12,400 மதிப்புள்ள 3 விற்பனையாளர் நிலுவைத் தொகைகள் செலுத்தப்பட வேண்டும். போதுமான நிதி உள்ளது.",
    insight3: "வரி சேமிப்பு வாய்ப்பு: உபகரண பில்லில் ₹4,200 முன்கூட்டிய ஜிஎஸ்டி உள்ளீட்டு வரி வரவு பெறலாம்.",
    insight4: "98.4% சரியான நேர செலுத்தல் புள்ளிகளுடன் கடன் தகுதி AAA ப்ரைமாக உயர்ந்துள்ளது.",

    // Expense Categories
    "Engineering & Infra": "பொறியியல் & கட்டமைப்பு",
    "Cloud & Hosting": "கிளவுட் & ஹோஸ்டிங்",
    "Office & Workspace": "அலுவலகம் & பணியிடம்",
    "Marketing & Growth": "சந்தைப்படுத்தல் & வளர்ச்சி",
    "Payroll & Legal": "ஊதியம் & சட்டம்",
    "Other Operating": "பிற இயக்கச் செலவுகள்",
    "Software & Subscriptions": "மென்பொருள் & சந்தாக்கள்",
    "Design & Creative": "வடிவமைப்பு & படைப்பாற்றல்",
    "Travel & Logistics": "பயணம் & தளவாடங்கள்",
    "Office Supplies": "அலுவலக பொருட்கள்",
    "Hardware & Servers": "வன்பொருள் & சேவையகங்கள்",
    "Security & Audits": "பாதுகாப்பு & தணிக்கைகள்",
    "Professional Fees": "தொழில்முறை கட்டணங்கள்",
  },

  hi: {
    // Navigation (हिन्दी)
    dashboard: "डैशबोर्ड",
    invoices: "चालान / इनवॉयस",
    expenses: "खर्चे",
    transactions: "लेन-देन",
    customers: "ग्राहक",
    payments: "भुगतान",
    credit: "क्रेडिट स्कोर",
    advisor: "AI वित्तीय सलाहकार",
    reports: "रिपोर्ट्स",
    settings: "सेटिंग्स",
    collapse: "छोटा करें",
    logout: "लॉग आउट",
    editProfile: "प्रोफ़ाइल संपादित करें",
    accountSettings: "खाता और सेटिंग्स",

    // Topbar
    searchPlaceholder: "लेन-देन, इनवॉयस खोजें…",
    notifications: "सूचनाएं",
    language: "भाषा",
    selectLanguage: "भाषा चुनें",

    // Timeframes
    "30 days": "30 दिन",
    "This month": "इस महीने",
    "Last 3 months": "पिछले 3 महीने",
    "This fiscal year": "यह वित्तीय वर्ष",

    // Dashboard Overview
    activePeriod: "सक्रिय अवधि",
    liveCalculated: "लाइव गणना",
    overviewTitle: "वित्तीय सारांश",
    totalRevenue: "कुल राजस्व",
    monthlyInflow: "मासिक आवक",
    operatingExpenses: "परिचालन व्यय",
    netCashFlow: "शुद्ध नकदी प्रवाह",
    runwayEstimate: "नकदी रनवे",
    runwayMonths: "महीने का रनवे मौजूदा खर्च पर",
    aiAdvisorTitle: "FinGuard AI वित्तीय सलाहकार",
    aiAdvisorSubtitle: "लाइव बिजनेस इंटेलिजेंस और नकदी अलर्ट",
    revenueVsExpenses: "राजस्व बनाम खर्च",
    comparison: "तुलना",
    revenue: "राजस्व",
    expenses: "खर्च",
    monthlyCashFlow: "मासिक नकदी प्रवाह",
    netCashPosition: "शुद्ध नकदी स्थिति, ₹ हजार में",
    netCash: "शुद्ध नकदी",
    expenseBreakdown: "खर्चों का विवरण",
    shareOfTotalSpend: "कुल खर्च में हिस्सा",
    paymentStatus: "भुगतान की स्थिति",
    invoicesThisPeriod: "इस अवधि के इनवॉयस",
    recentTransactions: "हाल के लेन-देन",
    viewAll: "सभी देखें",
    transaction: "लेन-देन",
    category: "श्रेणी",
    date: "तारीख",
    amount: "राशि",
    status: "स्थिति",
    recentInvoices: "हाल के इनवॉयस",
    due: "देय",
    preview: "पूर्वावलोकन",
    spendingScore: "खर्च स्कोर",
    creditScore: "क्रेडिट स्कोर",
    creditUtilization: "क्रेडिट उपयोग",
    monthlySpendingTrend: "मासिक खर्च का रुझान",
    last6Months: "पिछले 6 महीने",
    ptsVsLastMonth: "अंक पिछले महीने की तुलना में",

    // Invoices Page
    invoicesTitle: "इनवॉयस और बिलिंग",
    smartUploadAi: "स्मार्ट अपलोड (AI)",
    addManual: "मैनुअल जोड़ें",
    searchInvoices: "ग्राहक या इनवॉयस आईडी खोजें",
    all: "सभी",
    paid: "भुगतान हो गया",
    sent: "भेजा गया",
    dueSoon: "जल्द देय",
    overdue: "अवधि समाप्त",
    draft: "ड्राफ्ट",
    aiImported: "AI द्वारा आयातित",
    noInvoicesFound: "कोई इनवॉयस नहीं मिला",
    noInvoicesDesc: "अलग फ़िल्टर या खोज शब्द आज़माएं, या नया इनवॉयस अपलोड करें।",
    invoiceColumn: "इनवॉयस",
    customerColumn: "ग्राहक",
    dueDateColumn: "अंतिम तिथि",
    amountColumn: "राशि",
    statusColumn: "स्थिति",
    actionsColumn: "कार्रवाई",
    viewDetails: "विवरण देखें",

    // Invoice Detail & Reminder Modal
    invoiceDetailsTitle: "इनवॉयस विवरण",
    invoiceOverviewTab: "इनवॉयस अवलोकन और आइटम",
    remindCustomerTab: "ग्राहक को याद दिलाएं (ईमेल / WhatsApp)",
    remindToPay: "भुगतान की याद दिलाएं",
    markAsPaid: "भुगतान पूर्ण चिह्नित करें",
    markAsUnpaid: "अदत्त चिह्नित करें",
    billedTo: "ग्राहक विवरण",
    scheduleTerms: "शर्तें और तिथियां",
    invoiceDate: "इनवॉयस तिथि",
    terms: "नियम",
    totalAmountDue: "कुल देय राशि",
    itemizedBreakdown: "मदों का विवरण",
    items: "मदें",
    qty: "मात्रा",
    subtotal: "उप-योग",
    discount: "छूट",
    gstTax: "जीएसटी कर",
    totalDue: "कुल देय",
    reminderActivityLog: "रिमाइंडर गतिविधि लॉग",
    reminded: "याद दिलाया गया",
    printInvoice: "इनवॉयस प्रिंट करें",
    chooseChannel: "1. संचार माध्यम चुनें",
    whatsAppDirect: "सीधा WhatsApp",
    emailMailto: "ईमेल (Mailto)",
    aiWorkflow: "AI वर्कफ़्लो",
    targetRecipient: "प्राप्तकर्ता ग्राहक",
    pendingDue: "बकाया राशि",
    chooseTone: "2. संदेश का लहजा चुनें",
    friendly: "मित्रवत",
    urgent: "अति आवश्यक",
    official: "आधिकारिक",
    workflowWebhookUrl: "वर्कफ़्लो वेबहुक URL",
    hideJson: "JSON छिपाएं",
    viewJsonPayload: "JSON पेलोड देखें",
    reminderDraft: "3. रिमाइंडर संदेश का ड्राफ्ट",
    copyText: "टेक्स्ट कॉपी करें",
    copied: "कॉपी हो गया!",
    backToInvoice: "इनवॉयस पर वापस जाएं",
    sendOnWhatsApp: "WhatsApp पर भेजें",
    openEmailClient: "ईमेल ऐप में खोलें",
    triggerWorkflowWebhook: "AI वर्कफ़्लो वेबहुक ट्रिगर करें",
    triggeringWorkflow: "वर्कफ़्लो शुरू हो रहा है...",
    close: "बंद करें",
    cancel: "रद्द करें",

    // Smart Upload Modal
    smartUploadModalTitle: "स्मार्ट इनवॉयस और रसीद स्कैनर",
    neuralOcrActive: "न्यूरल OCR सक्रिय",
    smartUploadSubtext: "इनवॉयस छवियों और पीडीएफ को सीधे पढ़कर सही मदों और ग्राहक विवरणों को निकालता है",
    dragDropText: "यहाँ अपना इनवॉयस चित्र या PDF खींचें और छोड़ें",
    dragDropSubtext: "एबीसी किराना या किसी भी बिल को स्वचालित रूप से स्कैन करें और सभी वस्तुओं को निकालें।",
    browseImageOrPdf: "चित्र या PDF चुनें",
    supportedFormats: "समर्थित प्रारूप",
    pdfDocuments: "PDF दस्तावेज़",
    sampleTemplates: "या नमूना टेम्पलेट आज़माएं:",
    intelligentOcrScanner: "स्मार्ट OCR स्कैनर",
    ocrInfoBanner: "FinGuard AI आपके अपलोड किए गए बिल से टेक्स्ट और तालिकाओं को पढ़कर मदों, कीमतों, करों और ग्राहक विवरणों को निकालता है।",
    readingInvoice: "FinGuard AI आपका इनवॉयस पढ़ रहा है...",
    neuralOcrAnalysis: "न्यूरल OCR विश्लेषण",
    scanStep1: "बाइनरी फ़ाइल स्ट्रीम करना और OCR शुरू करना",
    scanStep2: "न्यूरल OCR: टेक्स्ट टोकन, पंक्तियाँ और आइटम पढ़ना",
    scanStep3: "ग्राहक और तिथियों का पता लगाना",
    scanStep4: "वस्तुओं की मात्रा, कर और योग की गणना करना",
    scanStep5: "FinGuard UI के साथ संरचित डेटा सिंक करना",
    uploadAnother: "दूसरा अपलोड करें",
    extractedInvoiceDetails: "निकाले गए इनवॉयस विवरण",
    clickToEdit: "संपादित करने के लिए क्लिक करें",
    invoiceNumber: "इनवॉयस नंबर",
    customerName: "ग्राहक का नाम",
    contactEmail: "संपर्क ईमेल",
    phoneNumber: "फ़ोन नंबर",
    billingAddress: "बिलिंग पता",
    extractedItems: "निकाले गए आइटम",
    addItem: "आइटम जोड़ें",
    gstTaxRate: "जीएसटी दर (%)",
    documentPreview: "दस्तावेज़ पूर्वावलोकन",
    uploadedImagePreview: "अपलोड किया गया चित्र",
    taxInvoicePreview: "टैक्स इनवॉयस",
    ocrVerifiedText: "ऑप्टिकल टेक्स्ट पहचान और कुल राशि सत्यापित",
    backToUpload: "वापस अपलोड पर जाएं",
    reviewAndAddInvoice: "समीक्षा करें और इनवॉयस जोड़ें",

    // Settings
    settingsDesc: "अपनी प्रोफ़ाइल, व्यावसायिक जानकारी, भाषा और सूचनाओं का प्रबंधन करें।",
    languageSettings: "भाषा और क्षेत्रीय सेटिंग्स",
    languageDescription: "अपनी पसंदीदा भाषा चुनें। सभी वित्तीय विश्लेषण, नेविगेशन और इनवॉयस टूल तुरंत अपडेट हो जाएंगे।",
    languageChangedTo: "भाषा बदल दी गई है:",
    userProfile: "उपयोगकर्ता प्रोफ़ाइल",
    editProfileDetails: "प्रोफ़ाइल विवरण संपादित करें",
    businessAccountDetails: "व्यावसायिक और खाता विवरण",
    yourFullName: "आपका पूरा नाम",
    roleDesignation: "पद / पदनाम",
    businessName: "व्यापार का नाम",
    profileSavedMsg: "परिवर्तन सफलतापूर्वक सहेजे गए।",
    signedOutMsg: "आप साइन आउट हो गए हैं।",
    saveChanges: "परिवर्तन सहेजें",
    notifInvoiceDue: "इनवॉयस देय होने पर सूचना दें",
    notifWeeklySummary: "साप्ताहिक वित्तीय सारांश भेजें",
    notifCreditAlerts: "क्रेडिट उपयोग में बदलाव पर सूचित करें",
    securityAndDatabase: "सुरक्षा और डेटाबेस स्थिति",
    persistentDatabase: "स्थानीय डेटाबेस",
    registeredAccountsStored: "पंजीकृत खाते संग्रहीत हैं",
    activeStorage: "सक्रिय स्टोरेज",
    registeredAccountsInDb: "डेटाबेस में पंजीकृत खाते:",
    current: "वर्तमान",
    sessionActiveFor: "सक्रिय सत्र:",

    // AI Advisor Panel Insights
    insight1: "हालिया भुगतानों के बाद एबीसी किराना का कैश फ्लो 14.2% बेहतर हुआ है।",
    insight2: "इस सप्ताह ₹12,400 के 3 विक्रेता भुगतान देय हैं। पर्याप्त तरलता उपलब्ध है।",
    insight3: "कर बचत अवसर: उपकरण इनवॉयस पर ₹4,200 का अग्रिम इनपुट जीएसटी दावा किया जा सकता है।",
    insight4: "98.4% समय पर भुगतान के साथ क्रेडिट रेटिंग सुधरकर AAA प्राइम हो गई है।",

    // Expense Categories
    "Engineering & Infra": "इंजीनियरिंग और इंफ्रा",
    "Cloud & Hosting": "क्लाउड और होस्टिंग",
    "Office & Workspace": "कार्यालय और कार्यक्षेत्र",
    "Marketing & Growth": "मार्केटिंग और विकास",
    "Payroll & Legal": "वेतन और कानूनी",
    "Other Operating": "अन्य परिचालन व्यय",
    "Software & Subscriptions": "सॉफ्टवेयर और सदस्यता",
    "Design & Creative": "डिज़ाइन और रचनात्मक",
    "Travel & Logistics": "यात्रा और लॉजिस्टिक्स",
    "Office Supplies": "कार्यालय सामग्री",
    "Hardware & Servers": "हार्डवेयर और सर्वर",
    "Security & Audits": "सुरक्षा और ऑडिट",
    "Professional Fees": "पेशेवर शुल्क",
  },

  es: {
    // Navigation (Español)
    dashboard: "Panel de Control",
    invoices: "Facturas",
    expenses: "Gastos",
    transactions: "Transacciones",
    customers: "Clientes",
    payments: "Pagos",
    credit: "Calificación Crediticia",
    advisor: "Asesor IA",
    reports: "Informes",
    settings: "Configuración",
    collapse: "Colapsar",
    logout: "Cerrar sesión",
    editProfile: "Editar perfil",
    accountSettings: "Cuenta y ajustes",

    // Topbar
    searchPlaceholder: "Buscar transacciones, facturas…",
    notifications: "Notificaciones",
    language: "Idioma",
    selectLanguage: "Seleccionar idioma",

    // Timeframes
    "30 days": "30 días",
    "This month": "Este mes",
    "Last 3 months": "Últimos 3 meses",
    "This fiscal year": "Este año fiscal",

    // Dashboard Overview
    activePeriod: "Período activo",
    liveCalculated: "Calculado en vivo",
    overviewTitle: "Resumen Financiero",
    totalRevenue: "Ingresos Totales",
    monthlyInflow: "Flujo Mensual",
    operatingExpenses: "Gastos Operativos",
    netCashFlow: "Flujo de Caja Neto",
    runwayEstimate: "Autonomía Financiera",
    runwayMonths: "meses de autonomía al ritmo actual",
    aiAdvisorTitle: "Asesor FinGuard IA",
    aiAdvisorSubtitle: "Inteligencia empresarial y alertas de liquidez",
    revenueVsExpenses: "Ingresos vs Gastos",
    comparison: "Comparación",
    revenue: "Ingresos",
    expenses: "Gastos",
    monthlyCashFlow: "Flujo de caja mensual",
    netCashPosition: "Posición neta de caja, en miles de ₹",
    netCash: "Caja neta",
    expenseBreakdown: "Desglose de Gastos",
    shareOfTotalSpend: "Participación en el gasto total",
    paymentStatus: "Estado de Pago",
    invoicesThisPeriod: "Facturas de este período",
    recentTransactions: "Transacciones recientes",
    viewAll: "Ver todo",
    transaction: "Transacción",
    category: "Categoría",
    date: "Fecha",
    amount: "Monto",
    status: "Estado",
    recentInvoices: "Facturas Recientes",
    due: "Vence",
    preview: "Vista previa",
    spendingScore: "Puntuación de gasto",
    creditScore: "Puntuación crediticia",
    creditUtilization: "Uso del crédito",
    monthlySpendingTrend: "Tendencia de gasto mensual",
    last6Months: "Últimos 6 meses",
    ptsVsLastMonth: "pts vs mes anterior",

    // Invoices Page
    invoicesTitle: "Facturas y Cobranzas",
    smartUploadAi: "Subida Inteligente (IA)",
    addManual: "Añadir manual",
    searchInvoices: "Buscar cliente o número de factura",
    all: "Todas",
    paid: "Pagada",
    sent: "Enviada",
    dueSoon: "Vence pronto",
    overdue: "Vencida",
    draft: "Borrador",
    aiImported: "Importado por IA",
    noInvoicesFound: "No se encontraron facturas",
    noInvoicesDesc: "Pruebe con otro filtro o suba una nueva factura.",
    invoiceColumn: "Factura",
    customerColumn: "Cliente",
    dueDateColumn: "Fecha límite",
    amountColumn: "Monto",
    statusColumn: "Estado",
    actionsColumn: "Acciones",
    viewDetails: "Ver detalles",

    // Invoice Detail & Reminder Modal
    invoiceDetailsTitle: "Detalles de la Factura",
    invoiceOverviewTab: "Resumen y Artículos",
    remindCustomerTab: "Recordar al Cliente (Correo / WhatsApp)",
    remindToPay: "Recordar Pago",
    markAsPaid: "Marcar como Pagada",
    markAsUnpaid: "Marcar como No Pagada",
    billedTo: "Facturado a (Cliente)",
    scheduleTerms: "Plazos y Condiciones",
    invoiceDate: "Fecha de Emisión",
    terms: "Términos",
    totalAmountDue: "Total a Pagar",
    itemizedBreakdown: "Desglose de Artículos",
    items: "artículos",
    qty: "Cant.",
    subtotal: "Subtotal",
    discount: "Descuento",
    gstTax: "Impuesto IVA/GST",
    totalDue: "Total Adeudado",
    reminderActivityLog: "Registro de Recordatorios",
    reminded: "Recordado",
    printInvoice: "Imprimir factura",
    chooseChannel: "1. Seleccione Canal de Notificación",
    whatsAppDirect: "WhatsApp Directo",
    emailMailto: "Correo Electrónico",
    aiWorkflow: "Flujo de Trabajo IA",
    targetRecipient: "Destinatario",
    pendingDue: "Saldo pendiente",
    chooseTone: "2. Seleccione el Tono",
    friendly: "Amable",
    urgent: "Urgente",
    official: "Oficial",
    workflowWebhookUrl: "URL Webhook del flujo de trabajo",
    hideJson: "Ocultar JSON",
    viewJsonPayload: "Ver carga útil JSON",
    reminderDraft: "3. Mensaje del Recordatorio",
    copyText: "Copiar texto",
    copied: "¡Copiado!",
    backToInvoice: "Volver a la Factura",
    sendOnWhatsApp: "Enviar por WhatsApp",
    openEmailClient: "Abrir en Correo",
    triggerWorkflowWebhook: "Ejecutar Flujo Webhook IA",
    triggeringWorkflow: "Ejecutando flujo...",
    close: "Cerrar",
    cancel: "Cancelar",

    // Smart Upload Modal
    smartUploadModalTitle: "Escáner Inteligente de Facturas y Recibos",
    neuralOcrActive: "OCR Neuronal Activo",
    smartUploadSubtext: "Lee imágenes de facturas y PDF directamente, extrayendo partidas y datos de clientes",
    dragDropText: "Arrastre y suelte su imagen o PDF de factura aquí",
    dragDropSubtext: "Suba cualquier recibo para escanear y extraer automáticamente los datos.",
    browseImageOrPdf: "Explorar Imagen o PDF",
    supportedFormats: "Formatos admitidos",
    pdfDocuments: "Documentos PDF",
    sampleTemplates: "O pruebe con plantillas de muestra:",
    intelligentOcrScanner: "Escáner OCR Inteligente",
    ocrInfoBanner: "FinGuard IA lee texto y tablas numéricas directamente de imágenes y recibos cargados, analizando automáticamente artículos, cantidades, precios e impuestos.",
    readingInvoice: "FinGuard IA está leyendo su factura...",
    neuralOcrAnalysis: "Análisis OCR Neuronal",
    scanStep1: "Transmitiendo archivo binario e iniciando escáner OCR",
    scanStep2: "OCR Neuronal: Lectura de texto, líneas y artículos",
    scanStep3: "Detección de clientes y fechas de facturación",
    scanStep4: "Cálculo de cantidades de artículos, impuestos y subtotal",
    scanStep5: "Sincronizando registro estructurado con FinGuard",
    uploadAnother: "Subir otra factura",
    extractedInvoiceDetails: "Detalles Extraídos de la Factura",
    clickToEdit: "Haga clic en cualquier campo para editar",
    invoiceNumber: "Número de Factura",
    customerName: "Nombre del Cliente (Facturado a)",
    contactEmail: "Correo de Contacto",
    phoneNumber: "Teléfono",
    billingAddress: "Dirección de Facturación",
    extractedItems: "Artículos Extraídos",
    addItem: "Añadir Artículo",
    gstTaxRate: "Tasa de Impuesto (%)",
    documentPreview: "Vista Previa del Documento",
    uploadedImagePreview: "Imagen Subida",
    taxInvoicePreview: "Factura Fiscal",
    ocrVerifiedText: "Reconocimiento óptico de texto y totales verificados",
    backToUpload: "Volver a Subir",
    reviewAndAddInvoice: "Revisar y Añadir Factura",

    // Settings
    settingsDesc: "Administre su perfil personal, datos comerciales, idioma y notificaciones.",
    languageSettings: "Ajustes de idioma y región",
    languageDescription: "Elija su idioma preferido. Todos los análisis financieros, navegación y herramientas de facturación se actualizarán al instante.",
    languageChangedTo: "Idioma cambiado a:",
    userProfile: "Perfil de usuario",
    editProfileDetails: "Editar detalles del perfil",
    businessAccountDetails: "Detalles comerciales y de cuenta",
    yourFullName: "Su nombre completo",
    roleDesignation: "Cargo / Puesto",
    businessName: "Nombre de la empresa",
    profileSavedMsg: "Cambios guardados con éxito.",
    signedOutMsg: "Ha cerrado sesión.",
    saveChanges: "Guardar cambios",
    notifInvoiceDue: "Avisarme cuando las facturas venzan pronto",
    notifWeeklySummary: "Enviar un resumen financiero semanal",
    notifCreditAlerts: "Notificarme sobre cambios en el uso del crédito",
    securityAndDatabase: "Seguridad y Base de Datos",
    persistentDatabase: "Base de datos local persistente",
    registeredAccountsStored: "cuenta(s) de usuario registrada(s) en la base de datos",
    activeStorage: "Almacenamiento activo",
    registeredAccountsInDb: "Cuentas registradas en la base de datos:",
    current: "Actual",
    sessionActiveFor: "Sesión activa para:",

    // AI Advisor Panel Insights
    insight1: "El flujo de caja mejoró un 14.2% tras el cobro de facturas recientes.",
    insight2: "3 pagos a proveedores vencen esta semana por ₹12,400. Liquidez suficiente.",
    insight3: "Oportunidad fiscal: Deducción de ₹4,200 en factura de equipamiento.",
    insight4: "Calificación crediticia elevada a AAA Prime con 98.4% de puntualidad.",

    // Expense Categories
    "Engineering & Infra": "Ingeniería e Infraestructura",
    "Cloud & Hosting": "Nube y Alojamiento",
    "Office & Workspace": "Oficina y Espacio de Trabajo",
    "Marketing & Growth": "Marketing y Crecimiento",
    "Payroll & Legal": "Nómina y Asuntos Legales",
    "Other Operating": "Otros Gastos Operativos",
    "Software & Subscriptions": "Software y Suscripciones",
    "Design & Creative": "Diseño y Creatividad",
    "Travel & Logistics": "Viajes y Logística",
    "Office Supplies": "Material de Oficina",
    "Hardware & Servers": "Hardware y Servidores",
    "Security & Audits": "Seguridad y Auditorías",
    "Professional Fees": "Honorarios Profesionales",
  },

  fr: {
    // Navigation (Français)
    dashboard: "Tableau de Bord",
    invoices: "Factures",
    expenses: "Dépenses",
    transactions: "Transactions",
    customers: "Clients",
    payments: "Paiements",
    credit: "Score de Crédit",
    advisor: "Conseiller IA",
    reports: "Rapports",
    settings: "Paramètres",
    collapse: "Réduire",
    logout: "Se déconnecter",
    editProfile: "Modifier le profil",
    accountSettings: "Compte et paramètres",

    // Topbar
    searchPlaceholder: "Rechercher transactions, factures…",
    notifications: "Notifications",
    language: "Langue",
    selectLanguage: "Choisir la langue",

    // Timeframes
    "30 days": "30 jours",
    "This month": "Ce mois-ci",
    "Last 3 months": "3 derniers mois",
    "This fiscal year": "Exercice fiscal",

    // Dashboard Overview
    activePeriod: "Période active",
    liveCalculated: "Calcul en direct",
    overviewTitle: "Aperçu Financier",
    totalRevenue: "Revenu Total",
    monthlyInflow: "Entrées Mensuelles",
    operatingExpenses: "Dépenses d'Exploitation",
    netCashFlow: "Flux de Trésorerie Net",
    runwayEstimate: "Autonomie de Trésorerie",
    runwayMonths: "mois d'autonomie au rythme actuel",
    aiAdvisorTitle: "Conseiller FinGuard IA",
    aiAdvisorSubtitle: "Intelligence d'affaires et alertes de trésorerie en direct",
    revenueVsExpenses: "Revenus vs Dépenses",
    comparison: "Comparaison",
    revenue: "Revenus",
    expenses: "Dépenses",
    monthlyCashFlow: "Flux de trésorerie mensuel",
    netCashPosition: "Position de trésorerie nette, en milliers de ₹",
    netCash: "Trésorerie nette",
    expenseBreakdown: "Répartition des Dépenses",
    shareOfTotalSpend: "Part des dépenses totales",
    paymentStatus: "Statut des Paiements",
    invoicesThisPeriod: "Factures de la période",
    recentTransactions: "Transactions récentes",
    viewAll: "Voir tout",
    transaction: "Transaction",
    category: "Catégorie",
    date: "Date",
    amount: "Montant",
    status: "Statut",
    recentInvoices: "Factures Récentes",
    due: "Échéance",
    preview: "Aperçu",
    spendingScore: "Score de dépenses",
    creditScore: "Score de crédit",
    creditUtilization: "Utilisation du crédit",
    monthlySpendingTrend: "Tendance mensuelle des dépenses",
    last6Months: "6 derniers mois",
    ptsVsLastMonth: "pts vs mois dernier",

    // Invoices Page
    invoicesTitle: "Factures et Facturation",
    smartUploadAi: "Import Intelligent (IA)",
    addManual: "Ajout manuel",
    searchInvoices: "Rechercher un client ou un numéro",
    all: "Toutes",
    paid: "Payée",
    sent: "Envoyée",
    dueSoon: "Bientôt due",
    overdue: "En retard",
    draft: "Brouillon",
    aiImported: "Importé par IA",
    noInvoicesFound: "Aucune facture trouvée",
    noInvoicesDesc: "Essayez un autre filtre ou importez une nouvelle facture.",
    invoiceColumn: "Facture",
    customerColumn: "Client",
    dueDateColumn: "Date d'échéance",
    amountColumn: "Montant",
    statusColumn: "Statut",
    actionsColumn: "Actions",
    viewDetails: "Voir les détails",

    // Invoice Detail & Reminder Modal
    invoiceDetailsTitle: "Détails de la Facture",
    invoiceOverviewTab: "Aperçu et Articles",
    remindCustomerTab: "Rappeler au Client (Email / WhatsApp)",
    remindToPay: "Rappeler le Paiement",
    markAsPaid: "Marquer comme Payée",
    markAsUnpaid: "Marquer comme Non Payée",
    billedTo: "Facturé à (Client)",
    scheduleTerms: "Échéances et Modalités",
    invoiceDate: "Date de Facturation",
    terms: "Conditions",
    totalAmountDue: "Montant Total Dû",
    itemizedBreakdown: "Détail des Articles",
    items: "articles",
    qty: "Qté",
    subtotal: "Sous-total",
    discount: "Remise",
    gstTax: "TVA / Taxe",
    totalDue: "Total Dû",
    reminderActivityLog: "Historique des Rappels",
    reminded: "Rappelé",
    printInvoice: "Imprimer la facture",
    chooseChannel: "1. Sélectionner le Canal",
    whatsAppDirect: "WhatsApp Direct",
    emailMailto: "Email (Mailto)",
    aiWorkflow: "Flux Automatisé IA",
    targetRecipient: "Destinataire",
    pendingDue: "Montant dû",
    chooseTone: "2. Choisir le Ton",
    friendly: "Courtois",
    urgent: "Urgent",
    official: "Officiel",
    workflowWebhookUrl: "URL Webhook du flux de travail",
    hideJson: "Masquer JSON",
    viewJsonPayload: "Voir le payload JSON",
    reminderDraft: "3. Projet de Message",
    copyText: "Copier le texte",
    copied: "Copié !",
    backToInvoice: "Retour à la Facture",
    sendOnWhatsApp: "Envoyer sur WhatsApp",
    openEmailClient: "Ouvrir dans l'application Mail",
    triggerWorkflowWebhook: "Déclencher le Webhook IA",
    triggeringWorkflow: "Déclenchement du flux...",
    close: "Fermer",
    cancel: "Annuler",

    // Smart Upload Modal
    smartUploadModalTitle: "Scanner Intelligent de Factures et Reçus",
    neuralOcrActive: "OCR Neuronal Actif",
    smartUploadSubtext: "Lit directement les images et PDF de factures, extrayant les articles et coordonnées",
    dragDropText: "Glissez-déposez votre image ou PDF de facture ici",
    dragDropSubtext: "Importez n'importe quel reçu pour extraire automatiquement tous les articles.",
    browseImageOrPdf: "Parcourir Image ou PDF",
    supportedFormats: "Formats pris en charge",
    pdfDocuments: "Documents PDF",
    sampleTemplates: "Ou essayez des modèles d'exemples :",
    intelligentOcrScanner: "Scanner OCR Intelligent",
    ocrInfoBanner: "FinGuard IA lit directement les tableaux numériques et textes, analysant les articles, quantités, prix et taxes.",
    readingInvoice: "FinGuard IA analyse votre facture...",
    neuralOcrAnalysis: "Analyse OCR Neuronale",
    scanStep1: "Transmission du fichier binaire et initialisation de l'OCR",
    scanStep2: "OCR Neuronal : Lecture des lignes et des articles",
    scanStep3: "Détection des informations clients et des dates",
    scanStep4: "Calcul des quantités, des taxes et du sous-total",
    scanStep5: "Synchronisation de la facture avec FinGuard",
    uploadAnother: "Importer une autre facture",
    extractedInvoiceDetails: "Détails Extraits de la Facture",
    clickToEdit: "Cliquez sur un champ pour modifier",
    invoiceNumber: "Numéro de Facture",
    customerName: "Nom du Client (Facturé à)",
    contactEmail: "Email de Contact",
    phoneNumber: "Numéro de Téléphone",
    billingAddress: "Adresse de Facturation",
    extractedItems: "Articles Extraits",
    addItem: "Ajouter un Article",
    gstTaxRate: "Taux de Taxe (%)",
    documentPreview: "Aperçu du Document",
    uploadedImagePreview: "Image Importée",
    taxInvoicePreview: "Facture Fiscale",
    ocrVerifiedText: "Reconnaissance optique et totaux vérifiés",
    backToUpload: "Retourner à l'Import",
    reviewAndAddInvoice: "Vérifier et Ajouter la Facture",

    // Settings
    settingsDesc: "Gérez votre profil personnel, vos informations professionnelles, votre langue et vos notifications.",
    languageSettings: "Paramètres de langue et région",
    languageDescription: "Choisissez votre langue préférée. Toutes les analyses financières, la navigation et les outils de facturation seront immédiatement mis à jour.",
    languageChangedTo: "Langue changée en :",
    userProfile: "Profil utilisateur",
    editProfileDetails: "Modifier le profil",
    businessAccountDetails: "Informations professionnelles et compte",
    yourFullName: "Votre nom complet",
    roleDesignation: "Poste / Titre",
    businessName: "Nom de l'entreprise",
    profileSavedMsg: "Modifications enregistrées avec succès.",
    signedOutMsg: "Vous avez été déconnecté.",
    saveChanges: "Enregistrer les modifications",
    notifInvoiceDue: "M'alerter lorsque les factures arrivent à échéance",
    notifWeeklySummary: "Envoyer un récapitulatif financier hebdomadaire",
    notifCreditAlerts: "M'alerter en cas de modification de l'utilisation du crédit",
    securityAndDatabase: "Sécurité et Base de données",
    persistentDatabase: "Base de données locale persistante",
    registeredAccountsStored: "compte(s) enregistré(s) dans la base de données",
    activeStorage: "Stockage actif",
    registeredAccountsInDb: "Comptes enregistrés dans la base de données :",
    current: "Actuel",
    sessionActiveFor: "Session active pour :",

    // AI Advisor Panel Insights
    insight1: "La trésorerie s'est améliorée de 14.2% suite aux récents règlements.",
    insight2: "3 paiements fournisseurs dus cette semaine pour ₹12,400. Liquidité suffisante.",
    insight3: "Optimisation fiscale : Déduction de TVA de ₹4,200 disponible sur la facture d'équipement.",
    insight4: "Note de crédit relevée à AAA Prime avec 98.4% de paiements à l'heure.",

    // Expense Categories
    "Engineering & Infra": "Ingénierie et Infrastructure",
    "Cloud & Hosting": "Cloud et Hébergement",
    "Office & Workspace": "Bureaux et Espaces de Travail",
    "Marketing & Growth": "Marketing et Croissance",
    "Payroll & Legal": "Paie et Affaires Juridiques",
    "Other Operating": "Autres Dépenses d'Exploitation",
    "Software & Subscriptions": "Logiciels et Abonnements",
    "Design & Creative": "Design et Création",
    "Travel & Logistics": "Voyages et Logistique",
    "Office Supplies": "Fournitures de Bureau",
    "Hardware & Servers": "Matériel et Serveurs",
    "Security & Audits": "Sécurité et Audits",
    "Professional Fees": "Honoraires Professionnels",
  },

  de: {
    // Navigation (Deutsch)
    dashboard: "Übersicht",
    invoices: "Rechnungen",
    expenses: "Ausgaben",
    transactions: "Transaktionen",
    customers: "Kunden",
    payments: "Zahlungen",
    credit: "Bonitätsbewertung",
    advisor: "KI-Finanzberater",
    reports: "Berichte",
    settings: "Einstellungen",
    collapse: "Einklappen",
    logout: "Abmelden",
    editProfile: "Profil bearbeiten",
    accountSettings: "Konto & Einstellungen",

    // Topbar
    searchPlaceholder: "Transaktionen, Rechnungen suchen…",
    notifications: "Benachrichtigungen",
    language: "Sprache",
    selectLanguage: "Sprache wählen",

    // Timeframes
    "30 days": "30 Tage",
    "This month": "Dieser Monat",
    "Last 3 months": "Letzte 3 Monate",
    "This fiscal year": "Laufendes Geschäftsjahr",

    // Dashboard Overview
    activePeriod: "Aktiver Zeitraum",
    liveCalculated: "Live berechnet",
    overviewTitle: "Finanzübersicht",
    totalRevenue: "Gesamteinnahmen",
    monthlyInflow: "Monatlicher Zufluss",
    operatingExpenses: "Betriebsausgaben",
    netCashFlow: "Netto-Cashflow",
    runwayEstimate: "Liquiditätsreichweite",
    runwayMonths: "Monate Reichweite bei aktuellem Verbrauch",
    aiAdvisorTitle: "FinGuard KI-Finanzberater",
    aiAdvisorSubtitle: "Live-Business-Intelligence und Liquiditätswarnungen",
    revenueVsExpenses: "Einnahmen vs Ausgaben",
    comparison: "Vergleich",
    revenue: "Einnahmen",
    expenses: "Ausgaben",
    monthlyCashFlow: "Monatlicher Cashflow",
    netCashPosition: "Netto-Cash-Position, in Tausend ₹",
    netCash: "Netto-Barmittel",
    expenseBreakdown: "Ausgabenaufteilung",
    shareOfTotalSpend: "Anteil an den Gesamtausgaben",
    paymentStatus: "Zahlungsstatus",
    invoicesThisPeriod: "Rechnungen in diesem Zeitraum",
    recentTransactions: "Aktuelle Transaktionen",
    viewAll: "Alle anzeigen",
    transaction: "Transaktion",
    category: "Kategorie",
    date: "Datum",
    amount: "Betrag",
    status: "Status",
    recentInvoices: "Aktuelle Rechnungen",
    due: "Fällig",
    preview: "Vorschau",
    spendingScore: "Ausgaben-Score",
    creditScore: "Bonitätsbewertung",
    creditUtilization: "Kreditinanspruchnahme",
    monthlySpendingTrend: "Monatlicher Ausgabentrend",
    last6Months: "Letzte 6 Monate",
    ptsVsLastMonth: "Pkt. ggü. Vormonat",

    // Invoices Page
    invoicesTitle: "Rechnungen & Abrechnung",
    smartUploadAi: "Smart Upload (KI)",
    addManual: "Manuell hinzufügen",
    searchInvoices: "Kunde oder Rechnungsnummer suchen",
    all: "Alle",
    paid: "Bezahlt",
    sent: "Gesendet",
    dueSoon: "Bald fällig",
    overdue: "Überfällig",
    draft: "Entwurf",
    aiImported: "KI-Importiert",
    noInvoicesFound: "Keine Rechnungen gefunden",
    noInvoicesDesc: "Versuchen Sie einen anderen Filter oder laden Sie eine neue Rechnung hoch.",
    invoiceColumn: "Rechnung",
    customerColumn: "Kunde",
    dueDateColumn: "Fälligkeitsdatum",
    amountColumn: "Betrag",
    statusColumn: "Status",
    actionsColumn: "Aktionen",
    viewDetails: "Details anzeigen",

    // Invoice Detail & Reminder Modal
    invoiceDetailsTitle: "Rechnungsdetails",
    invoiceOverviewTab: "Übersicht & Posten",
    remindCustomerTab: "Kunden erinnern (E-Mail / WhatsApp)",
    remindToPay: "Zahlung anmahnen",
    markAsPaid: "Als bezahlt markieren",
    markAsUnpaid: "Als unbezahlt markieren",
    billedTo: "Rechnungsempfänger",
    scheduleTerms: "Fristen & Zahlungsbedingungen",
    invoiceDate: "Rechnungsdatum",
    terms: "Konditionen",
    totalAmountDue: "Gesamtbetrag fällig",
    itemizedBreakdown: "Postenaufstellung",
    items: "Posten",
    qty: "Menge",
    subtotal: "Zwischensumme",
    discount: "Rabatt",
    gstTax: "MwSt. / Steuer",
    totalDue: "Gesamtbetrag",
    reminderActivityLog: "Mahnungsverlauf",
    reminded: "Erinnert am",
    printInvoice: "Rechnung drucken",
    chooseChannel: "1. Benachrichtigungskanal wählen",
    whatsAppDirect: "WhatsApp Direkt",
    emailMailto: "E-Mail (Mailto)",
    aiWorkflow: "KI-Workflow",
    targetRecipient: "Empfänger",
    pendingDue: "Fälliger Betrag",
    chooseTone: "2. Tonalität wählen",
    friendly: "Freundlich",
    urgent: "Dringend",
    official: "Offiziell",
    workflowWebhookUrl: "Workflow-Webhook-URL",
    hideJson: "JSON ausblenden",
    viewJsonPayload: "JSON-Nutzlast anzeigen",
    reminderDraft: "3. Mahnungstext Entwurf",
    copyText: "Text kopieren",
    copied: "Kopiert!",
    backToInvoice: "Zurück zur Rechnung",
    sendOnWhatsApp: "Über WhatsApp senden",
    openEmailClient: "Im E-Mail-Programm öffnen",
    triggerWorkflowWebhook: "KI-Workflow-Webhook ausführen",
    triggeringWorkflow: "Workflow wird ausgeführt...",
    close: "Schließen",
    cancel: "Abbrechen",

    // Smart Upload Modal
    smartUploadModalTitle: "Intelligenter Rechnungs- & Beleg-Scanner",
    neuralOcrActive: "Neuronale OCR Aktiv",
    smartUploadSubtext: "Liest Rechnungsbilder und PDFs direkt aus und extrahiert Posten und Kundendaten",
    dragDropText: "Rechnungsbild oder PDF hierher ziehen",
    dragDropSubtext: "Laden Sie einen Beleg hoch, um alle Posten automatisch zu extrahieren.",
    browseImageOrPdf: "Bild oder PDF auswählen",
    supportedFormats: "Unterstützte Formate",
    pdfDocuments: "PDF-Dokumente",
    sampleTemplates: "Oder mit Beispielvorlagen testen:",
    intelligentOcrScanner: "Intelligenter OCR-Scanner",
    ocrInfoBanner: "FinGuard KI liest Text und Tabellen direkt aus Belegen und extrahiert automatisch Posten, Mengen, Preise und Steuern.",
    readingInvoice: "FinGuard KI liest Ihre Rechnung...",
    neuralOcrAnalysis: "Neuronale OCR-Analyse",
    scanStep1: "Binärdatei übertragen & OCR-Scanner initialisieren",
    scanStep2: "Neuronale OCR: Text-Token, Zeilen & Posten erfassen",
    scanStep3: "Kunden und Fälligkeitsdaten erkennen",
    scanStep4: "Mengen, Steuern und Zwischensumme berechnen",
    scanStep5: "Strukturierte Daten mit FinGuard synchronisieren",
    uploadAnother: "Weitere Rechnung hochladen",
    extractedInvoiceDetails: "Extrahierte Rechnungsdetails",
    clickToEdit: "Klicken Sie auf ein Feld zum Bearbeiten",
    invoiceNumber: "Rechnungsnummer",
    customerName: "Kundenname (Empfänger)",
    contactEmail: "Kontakt-E-Mail",
    phoneNumber: "Telefonnummer",
    billingAddress: "Rechnungsadresse",
    extractedItems: "Extrahierte Posten",
    addItem: "Posten hinzufügen",
    gstTaxRate: "Steuersatz (%)",
    documentPreview: "Dokumentenvorschau",
    uploadedImagePreview: "Hochgeladenes Bild",
    taxInvoicePreview: "Steuerrechnung",
    ocrVerifiedText: "Optische Texterkennung und Summen geprüft",
    backToUpload: "Zurück zum Upload",
    reviewAndAddInvoice: "Prüfen & Rechnung hinzufügen",

    // Settings
    settingsDesc: "Verwalten Sie Ihr persönliches Profil, Geschäftsdaten, Spracheinstellungen und Benachrichtigungen.",
    languageSettings: "Sprach- und Regionaleinstellungen",
    languageDescription: "Wählen Sie Ihre bevorzugte Sprache. Alle Finanzanalysen, Navigation und Rechnungstools werden sofort aktualisiert.",
    languageChangedTo: "Sprache geändert zu:",
    userProfile: "Benutzerprofil",
    editProfileDetails: "Profildetails bearbeiten",
    businessAccountDetails: "Geschäfts- & Kontodetails",
    yourFullName: "Ihr vollständiger Name",
    roleDesignation: "Rolle / Bezeichnung",
    businessName: "Unternehmensname",
    profileSavedMsg: "Änderungen erfolgreich gespeichert.",
    signedOutMsg: "Sie wurden abgemeldet.",
    saveChanges: "Änderungen speichern",
    notifInvoiceDue: "Benachrichtigen, wenn Rechnungen bald fällig sind",
    notifWeeklySummary: "Wöchentliche Finanzübersicht senden",
    notifCreditAlerts: "Über Änderungen der Kreditinanspruchnahme informieren",
    securityAndDatabase: "Sicherheit & Dummy-Datenbank",
    persistentDatabase: "Persistente lokale Datenbank",
    registeredAccountsStored: "registrierte Benutzerkonten in der Datenbank",
    activeStorage: "Aktiver Speicher",
    registeredAccountsInDb: "Registrierte Konten in der Datenbank:",
    current: "Aktuell",
    sessionActiveFor: "Sitzung aktiv für:",

    // AI Advisor Panel Insights
    insight1: "Der Cashflow hat sich nach jüngsten Zahlungseingängen um 14.2% verbessert.",
    insight2: "3 Lieferantenzahlungen über ₹12,400 diese Woche fällig. Ausreichende Liquidität vorhanden.",
    insight3: "Steueroptimierung: Vorsteuerabzug von ₹4,200 auf Ausrüstungsrechnung möglich.",
    insight4: "Bonitätsbewertung auf AAA Prime gestiegen mit 98.4% Pünktlichkeitsquote.",

    // Expense Categories
    "Engineering & Infra": "Entwicklung & Infrastruktur",
    "Cloud & Hosting": "Cloud & Hosting",
    "Office & Workspace": "Büro & Arbeitsplatz",
    "Marketing & Growth": "Marketing & Wachstum",
    "Payroll & Legal": "Gehälter & Rechtliches",
    "Other Operating": "Sonstige Betriebsausgaben",
    "Software & Subscriptions": "Software & Abonnements",
    "Design & Creative": "Design & Kreativität",
    "Travel & Logistics": "Reisen & Logistik",
    "Office Supplies": "Büromaterial",
    "Hardware & Servers": "Hardware & Server",
    "Security & Audits": "Sicherheit & Audits",
    "Professional Fees": "Beratungskosten",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    try {
      const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY);
      if (stored && SUPPORTED_LANGUAGES.some((l) => l.code === stored)) {
        return stored;
      }
    } catch {}
    return "en";
  });

  const setLanguage = (langCode) => {
    if (SUPPORTED_LANGUAGES.some((l) => l.code === langCode)) {
      setLanguageState(langCode);
      try {
        localStorage.setItem(LANGUAGE_STORAGE_KEY, langCode);
        document.documentElement.lang = langCode;
      } catch {}
    }
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const currentLangObj =
    SUPPORTED_LANGUAGES.find((l) => l.code === language) || SUPPORTED_LANGUAGES[0];

  /**
   * Helper function to translate a key into the currently selected language.
   * If key is not found in the current language, falls back to English, then to provided fallback or key itself.
   */
  const t = (key, fallback = null) => {
    if (!key) return "";
    const langDict = TRANSLATIONS[language];
    if (langDict && langDict[key] !== undefined) {
      return langDict[key];
    }
    const enDict = TRANSLATIONS["en"];
    if (enDict && enDict[key] !== undefined) {
      return enDict[key];
    }
    return fallback !== null ? fallback : key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        currentLangObj,
        supportedLanguages: SUPPORTED_LANGUAGES,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
