import React, { useState } from "react";
import {
  X,
  CheckCircle2,
  Clock,
  AlertTriangle,
  Copy,
  Check,
  Printer,
  Download,
  ArrowDownLeft,
  ArrowUpRight,
  CreditCard,
  Building2,
  Calendar,
  FileText,
  ShieldCheck,
  RefreshCw,
  Hash,
} from "lucide-react";
import { formatINR } from "../data/mockData";
import { useToast } from "./ui";

export default function TransactionSlipModal({ transaction, open, onClose, onUpdateStatus }) {
  const [copied, setCopied] = useState(false);
  const [isRetrying, setIsRetrying] = useState(false);
  const push = useToast();

  if (!open || !transaction) return null;

  const isCredit = transaction.type === "credit" || transaction.amount > 0;
  const absAmount = Math.abs(transaction.amount);

  const handleCopy = (text, label = "Reference UTR") => {
    navigator.clipboard?.writeText(text);
    setCopied(true);
    push(`Copied ${label} to clipboard!`, "info");
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadReceipt = () => {
    const receiptData = `
========================================
         FINGUARD AI TRANSACTION SLIP
========================================
Transaction ID : ${transaction.id}
Reference / UTR: ${transaction.ref || "N/A"}
Party          : ${transaction.party}
Type           : ${isCredit ? "CREDIT (INFLOW)" : "DEBIT (OUTFLOW)"}
Category       : ${transaction.category}
Date & Time    : ${transaction.date} · ${transaction.time || "12:00 IST"}
Payment Method : ${transaction.method || "Electronic Transfer"}
Status         : ${transaction.status.toUpperCase()}
Amount         : ${isCredit ? "+" : "-"}₹${absAmount.toLocaleString("en-IN")}
Memo / Notes   : ${transaction.notes || "None"}
========================================
Generated by FinGuard AI Enterprise Ledger
Audit Verification Hash: ${Math.random().toString(36).substring(2, 12).toUpperCase()}
========================================
    `.trim();

    const blob = new Blob([receiptData], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `Receipt-${transaction.id}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    push("Transaction slip downloaded!", "success");
  };

  const handleStatusChange = (newStatus) => {
    if (newStatus === "Completed" && transaction.status === "Failed") {
      setIsRetrying(true);
      setTimeout(() => {
        setIsRetrying(false);
        onUpdateStatus?.(transaction.id, newStatus);
        push(`Transaction ${transaction.id} re-processed & cleared!`, "success");
      }, 700);
    } else {
      onUpdateStatus?.(transaction.id, newStatus);
      push(`Transaction status updated to ${newStatus}.`, "success");
    }
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 p-4 backdrop-blur-sm animate-[fadeIn_.15s_ease-out]"
      onClick={onClose}
    >
      <div
        className="w-full max-w-lg overflow-hidden rounded-2xl bg-white dark:bg-[#0C1322] border border-slate-200/90 dark:border-slate-800 shadow-[0_25px_70px_rgba(0,0,0,0.4)] transition-all"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header Ribbon */}
        <div
          className={`relative px-6 py-5 text-white ${
            isCredit
              ? "bg-gradient-to-r from-emerald-700 via-teal-700 to-cyan-700"
              : transaction.status === "Failed"
              ? "bg-gradient-to-r from-rose-800 via-red-700 to-rose-900"
              : "bg-gradient-to-r from-slate-900 via-blue-950 to-slate-900"
          }`}
        >
          <button
            onClick={onClose}
            className="absolute right-4 top-4 rounded-full p-1.5 text-white/70 hover:bg-white/10 hover:text-white transition-colors cursor-pointer"
            aria-label="Close"
          >
            <X size={18} />
          </button>

          <div className="flex items-center gap-2 text-xs font-semibold tracking-wider uppercase text-white/80 mb-1">
            <ShieldCheck size={16} className="text-white/90" />
            FinGuard Digital Voucher & Receipt
          </div>

          <div className="flex items-center justify-between">
            <h3 className="font-display text-2xl font-bold tracking-tight text-white">
              {transaction.id}
            </h3>
            <span
              className={`rounded-full px-3 py-1 text-xs font-bold tracking-wide uppercase border ${
                transaction.status === "Completed"
                  ? "bg-emerald-500/20 text-emerald-200 border-emerald-300/40"
                  : transaction.status === "Pending"
                  ? "bg-amber-500/20 text-amber-200 border-amber-300/40"
                  : "bg-rose-500/20 text-rose-200 border-rose-300/40"
              }`}
            >
              {transaction.status}
            </span>
          </div>
        </div>

        {/* Slip Body */}
        <div className="p-6 space-y-5 max-h-[70vh] overflow-y-auto">
          {/* Main Amount Card */}
          <div className="flex flex-col items-center justify-center p-5 rounded-2xl bg-slate-50/80 dark:bg-slate-900/60 border border-slate-200/80 dark:border-slate-800/80 text-center">
            <div className="flex items-center gap-1.5 mb-1 text-xs font-bold uppercase tracking-wider">
              {isCredit ? (
                <span className="flex items-center gap-1 text-emerald-600 dark:text-emerald-400">
                  <ArrowDownLeft size={16} /> Inflow (Credit)
                </span>
              ) : (
                <span className="flex items-center gap-1 text-slate-600 dark:text-slate-300">
                  <ArrowUpRight size={16} /> Outflow (Debit)
                </span>
              )}
            </div>
            <div
              className={`font-display text-3xl font-extrabold tracking-tight tabular ${
                isCredit
                  ? "text-emerald-600 dark:text-emerald-400"
                  : "text-slate-900 dark:text-white"
              }`}
            >
              {isCredit ? "+" : "-"}
              {formatINR(absAmount)}
            </div>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
              Paid {isCredit ? "from" : "to"}{" "}
              <strong className="text-slate-800 dark:text-slate-200 font-semibold">
                {transaction.party}
              </strong>
            </p>
          </div>

          {/* Key Details Grid */}
          <div className="grid grid-cols-2 gap-3.5 text-xs">
            <div className="p-3 rounded-xl border border-slate-100 dark:border-slate-800/80 bg-slate-50/50 dark:bg-slate-900/40">
              <span className="text-slate-400 dark:text-slate-500 block mb-1 font-medium">Payment Rail</span>
              <div className="flex items-center gap-1.5 font-bold text-slate-900 dark:text-white">
                <CreditCard size={14} className="text-blue-500" />
                {transaction.method || "Direct Bank Transfer"}
              </div>
            </div>

            <div className="p-3 rounded-xl border border-slate-100 dark:border-slate-800/80 bg-slate-50/50 dark:bg-slate-900/40">
              <span className="text-slate-400 dark:text-slate-500 block mb-1 font-medium">Category</span>
              <div className="flex items-center gap-1.5 font-bold text-slate-900 dark:text-white">
                <Building2 size={14} className="text-indigo-500" />
                {transaction.category}
              </div>
            </div>

            <div className="p-3 rounded-xl border border-slate-100 dark:border-slate-800/80 bg-slate-50/50 dark:bg-slate-900/40">
              <span className="text-slate-400 dark:text-slate-500 block mb-1 font-medium">Date & Timestamp</span>
              <div className="flex items-center gap-1.5 font-bold text-slate-900 dark:text-white">
                <Calendar size={14} className="text-teal-500" />
                {transaction.date} {transaction.time ? `· ${transaction.time}` : ""}
              </div>
            </div>

            <div className="p-3 rounded-xl border border-slate-100 dark:border-slate-800/80 bg-slate-50/50 dark:bg-slate-900/40">
              <span className="text-slate-400 dark:text-slate-500 block mb-1 font-medium">Verification Status</span>
              <div className="flex items-center gap-1.5 font-bold text-slate-900 dark:text-white">
                {transaction.status === "Completed" && <CheckCircle2 size={14} className="text-emerald-500" />}
                {transaction.status === "Pending" && <Clock size={14} className="text-amber-500" />}
                {transaction.status === "Failed" && <AlertTriangle size={14} className="text-rose-500" />}
                {transaction.status}
              </div>
            </div>
          </div>

          {/* Reference / UTR Number */}
          <div className="flex items-center justify-between rounded-xl border border-dashed border-slate-200 dark:border-slate-800 bg-slate-50/60 dark:bg-slate-900/50 p-3">
            <div className="flex items-center gap-2">
              <Hash size={16} className="text-slate-400" />
              <div>
                <p className="text-[11px] text-slate-400 dark:text-slate-500 font-medium">Bank Reference / UTR</p>
                <p className="font-mono text-xs font-bold text-slate-900 dark:text-white">
                  {transaction.ref || `UTR${transaction.id.replace("TXN-", "892")}`}
                </p>
              </div>
            </div>
            <button
              type="button"
              onClick={() => handleCopy(transaction.ref || transaction.id, "Reference")}
              className="flex items-center gap-1 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 px-2.5 py-1 text-xs font-semibold text-slate-700 dark:text-slate-300 hover:text-blue-600 dark:hover:text-blue-400 transition-colors cursor-pointer"
            >
              {copied ? <Check size={13} className="text-emerald-500" /> : <Copy size={13} />}
              {copied ? "Copied" : "Copy"}
            </button>
          </div>

          {/* Notes / Memo */}
          {transaction.notes && (
            <div className="rounded-xl border border-slate-100 dark:border-slate-800/80 bg-slate-50/40 dark:bg-slate-900/30 p-3">
              <span className="text-[11px] text-slate-400 dark:text-slate-500 font-medium flex items-center gap-1 mb-1">
                <FileText size={12} /> Transaction Memo / Audit Trail
              </span>
              <p className="text-xs text-slate-700 dark:text-slate-300 leading-relaxed font-medium">
                {transaction.notes}
              </p>
            </div>
          )}

          {/* Status Actions */}
          <div className="pt-2 border-t border-slate-100 dark:border-slate-800/80 flex items-center justify-between gap-2">
            <div className="text-xs font-medium text-slate-500 dark:text-slate-400">
              Quick status actions:
            </div>
            <div className="flex items-center gap-2">
              {transaction.status === "Pending" && (
                <button
                  type="button"
                  onClick={() => handleStatusChange("Completed")}
                  className="flex items-center gap-1.5 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white px-3 py-1.5 text-xs font-semibold shadow-sm transition-all cursor-pointer"
                >
                  <CheckCircle2 size={13} />
                  Mark as Cleared
                </button>
              )}
              {transaction.status === "Failed" && (
                <button
                  type="button"
                  disabled={isRetrying}
                  onClick={() => handleStatusChange("Completed")}
                  className="flex items-center gap-1.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white px-3 py-1.5 text-xs font-semibold shadow-sm transition-all cursor-pointer"
                >
                  <RefreshCw size={13} className={isRetrying ? "animate-spin" : ""} />
                  {isRetrying ? "Re-processing..." : "Re-try Settlement"}
                </button>
              )}
              {transaction.status === "Completed" && (
                <button
                  type="button"
                  onClick={() => handleStatusChange("Pending")}
                  className="flex items-center gap-1 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700 px-3 py-1.5 text-xs font-medium transition-colors cursor-pointer"
                >
                  <Clock size={13} />
                  Mark as Pending
                </button>
              )}
            </div>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="flex items-center justify-between border-t border-slate-100 dark:border-slate-800 bg-slate-50/70 dark:bg-slate-900/70 px-6 py-4">
          <button
            type="button"
            onClick={handlePrint}
            className="flex items-center gap-1.5 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-800/80 px-3.5 py-2 text-xs font-semibold text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors cursor-pointer"
          >
            <Printer size={14} />
            Print Slip
          </button>
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handleDownloadReceipt}
              className="flex items-center gap-1.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 text-xs font-semibold shadow-md shadow-blue-500/20 transition-all cursor-pointer"
            >
              <Download size={14} />
              Download Slip
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
